### ISSUE TITLE
Macro not working with closures

### ISSUE THREAD

**Issue by ray-delossantos** [jangko/nimLUA#1]
Maybe this is a problem of the macro transpiler/compiler from nim to c.

```
import nimLUA, os

proc main() =

  let test = 1

  proc abc(a, b: int): int =
    result =  test + a + b

  var L = newNimLua()
  L.bindFunction(abc)

  if L.doString(" print( abc(3,2) ) ") != 0.cint:
    echo L.toString(-1)
    L.pop(1)
  else:
    echo "Working properly"

  L.close()

main()

```

Error: execution of an external compiler program 'gcc -c  -w -O3 -fno-strict-aliasing  -I/home/perspectiva/nim/Nim/lib -o /home/perspectiva/apps/test/src/nimcache/test_test.o /home/perspectiva/apps/test/src/nimcache/test_test.c' failed with exit code: 256

/home/perspectiva/apps/test/src/nimcache/test_test.c: In function ‘main_154004’:
/home/perspectiva/apps/test/src/nimcache/test_test.c:379:2: error: incompatible type for argument 2 of ‘pushcfunction_101433’
  pushcfunction_101433(L, LOC1);
  ^
In file included from /home/perspectiva/apps/test/src/nimcache/test_test.c:9:0:
/home/perspectiva/apps/test/src/nimcache/test_test.c:261:23: note: expected ‘Tcfunction100650’ but argument is of type ‘TY154031’
 static N_INLINE(void, pushcfunction_101433)(void\* L, Tcfunction100650 fn) {
                       ^
/home/perspectiva/nim/Nim/lib/nimbase.h:44:50: note: in definition of macro ‘N_INLINE’
 #  define N_INLINE(rettype, name) inline rettype name
                                                  ^

**Comment by jangko** [comment]
yeah, that is Nim's compiler bug, possibly related to lambda lifting or codegen
theoretically, it is possible to implement closure vs. regular proc detection inside macro, but there will be a lot of work to do, maybe future version of nimLUA will implement that functionality.
as a shortcut, i think i will implement syntax extension to mark a proc as closure before feed them to VM
anyway, nimLUA still under heavy development process, many things come and go. 
for now this issue will be marked as feature request

**Comment by ray-delossantos** [comment]
@jangko , excellent library by the way, i'm trying to modify the macros to allow the closure behavior and maybe delivering a PR for your project, any tips on where to begin to modify nimLUA?

**Comment by jangko** [comment]
thanks, any help will be greatly appreciated.

**basic idea**:
nimLUA depends on macros.**bindSym** and macros.**getImpl** beside others things from macros module. but because bindSym only accept string literal and nothing else, its a bit tricky to use it.
that's why nimLUA perform two layer macro expansion.
**first layer**: when you call bindXXX, which in turn will call genProxyMacro. genProxyMacro as its name implies responsible to generate a proxy macro. you can inspect what really happened inside genProxyMacro by printing out it's input param and it's resulting code.

``` nimrod
echo  arg.treeRepr #see what passed into genProxyMacro

echo nlb #see the result near the bottom of genProxyMacro
result = parseCode(nlb)
```
- then from inside generated proxy macro, compile time procs like bindXXXImpl will be called.
- from inside bindXXXImpl, the second layer macro expanded to generate final glue code.
  again, you can inspect both the input params and output result to see what really happened.

as a start, you can try to play with this code:

``` nimrod
proc bindClosureImpl*(SL, libName: string, libKind: NimNodeKind, arg: openArray[elemTup]): NimNode {.compileTime.} =
#put your code here

macro bindClosure*(arg: varargs[untyped]): stmt =
  result = genProxyMacro(arg, {nlbUseLib}, "Closure")
```

because you want to generate glue code for closure, system.**rawProc** and system.**rawEnv** is your friend here, plus some casting.

the rest of it is practically type checking and data conversion between Nim types and Lua 'C' API

``` nimrod
  elemTup = tuple[
    node: NimNode, #this is nnkSym or nnkClosedSymChoice node generated by bindSym, bindXXXImpl will then use getImpl to get the AST body of proc/const/enum/etc implementation
    name: string, #newname that will be exported, taken from  abc -> "newname", or oldname if no newname supplied
    kind: NimNodeKind, #op '->' lhs kind, it could be nnkIdent or nnkAccQuoted
    rhsKind: NimNodeKind #op '->' rhs kind, it could be nnkNone or nnkStrLit or nnkIdent
  ]
```

**Comment by ray-delossantos** [comment]
The problem is not related to the macro but to the lua.nim file:

`proc pushcfunction*(L: PState; fn: TCfunction) {.inline.} = L.pushCclosure(fn, 0)`

Closures change the parameters and generate a different type other than a TCfunction.

I tried creating manually the code (without macros) for the closure proc and the error is also emitted.

**Comment by jangko** [comment]
no, lua.nim is ok.
what you should do is generating something like this(a bit dirty and polluting lua global namespace, but it works):

``` nimrod
  type
    abcd = proc(a, b: int, x:pointer): int {.nimcall.}

  L.pushLightUserData rawProc(abc)
  L.setGlobal("abcProc")
  L.pushLightUserData rawEnv(abc)
  L.setGlobal("abcEnv")

  proc nimLUAproxy0(L: PState): cint {.cdecl.} =
    var arg0 = L.checkInteger(1).int
    var arg1 = L.checkInteger(2).int
    L.getGlobal("abcProc")
    let p = cast[abcd](L.toUserData(-1))
    L.getGlobal("abcEnv")
    let env = L.toUserData(-1)
    L.pop(2)
    L.pushInteger(lua_Integer(p(arg0, arg1, env)))
    return 1

  L.pushCfunction(nimLUAproxy0)
  L.setGlobal("abc")
```

**Comment by ray-delossantos** [comment]
Sorry for my misleading comment. Thanks for the clarification. I'm too new to nim and lua c bindings for helping you with the library, 
i'll keep watching the evolution of this interesting project.

**Comment by jangko** [comment]
it's OK. if you cannot make a PR, testing and reporting bugs also very valuable

**Comment by jangko** [comment]
now you can bind closures, generic procs, property accessor with following syntax:

``` nimrod
L.bindFunction:
   [abc]                      #bind closure
   def[int, string, etc]      #bind generic proc

L.bindObject(Foo):
   speed(get, set)           #bind prop accessor
```
