### ISSUE TITLE
Wrong behavior when importing other libraries

### ISSUE THREAD

**Issue by ray-delossantos** [jangko/nimLUA#19]
Hi @jangko : 

Thx for this excellent library. Found some bugs when importing other nim libs:

Example:

```nim
import nimLUA, os, sequtils, logging


type
  Foo = ref object
    name: string

proc newFoo(name: string): Foo =
  new(result)
  result.name = name

proc addv(f: Foo, a, b: int): int =
  result = 2 * (a + b)

proc addv(f: Foo, a, b: string): string =
  result = "hello: my name is , here is my message: "

var L = newNimLua()
L.bindObject(Foo):
  newFoo -> constructor
  addv

L.dostring """ 
local foo = Foo.new("test")
print(foo:addv(1,2))
print(foo:addv("test","test"))
"""
L.close()
```

If i add logging it won't compile with the latest nim (0.19.4 [MacOSX: amd64]):

```
/nim-0.19.4/lib/core/macros.nim(510, 11) Error: type mismatch: got <PState>
```

EDIT:

The problem when importing  sequtils, json, random is that the polymorphism stop working and only the 
```proc addv(f: Foo, a, b: string): string``` 
get called twice.

```
import nimLUA, os, sequtils, json, random
```

returns : 
```
hello: my name is , here is my message:
hello: my name is , here is my message:
```

**Comment by jangko** [comment]
Thank you for reporting this. 
Recent Nim versions, from 0.19.0 to 0.20.0(under development) introduces a lot of breaking changes.
I will not fix this problem until Nim compiler a bit stable.
also nimLUA itself born when Nim lack of some useful features that can make it easier to debug and maintain.
the truth is, nimLUA needs rewrite for major portions of its code.
